name: OWASP Dependency-Check

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [master]

jobs:
  dependency-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache ODC data
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository/org/owasp/dependency-check-data
          key: ${{ runner.os }}-odc
          restore-keys: ${{ runner.os }}-odc

      - name: Run OWASP Dependency-Check
        uses: dependency-check/Dependency-Check_Action@v4.0.1
        with:
          project: "BPCalculator"
          path: "."
          format: "HTML"
          out: "odc-report"
          fail_on_cvss: "7"

      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: odc-report
