name: OWASP Dependency-Check

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:
  dependency-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Cache OWASP DC data
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository/org/owasp/dependency-check-data
          key: ${{ runner.os }}-odc
          restore-keys: ${{ runner.os }}-odc

      - name: Run OWASP Dependency-Check (NuGet + JS)
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: "BPCalculator"
          path: "."
          format: "HTML"
          out: "odc-report"
          args: >
            --scan .
            --enableExperimental
            --failOnCVSS 7
            --nvdApiDelay 2000

      - name: Upload Dependency-Check Report
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: odc-report
